spring.application.name=booking-system

# MongoDB Configuration (Local - No Authentication)
spring.data.mongodb.uri=mongodb://localhost:27017/booking_system

# Server Configuration
server.port=8080

# Logging (helpful for debugging)
logging.level.com.booking_system=DEBUG
logging.level.org.springframework.data.mongodb=DEBUG

# RabbitMQ Configuration
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=bookinguser
spring.rabbitmq.password=bookingpass123
spring.rabbitmq.virtual-host=/

# JSON Message Converter
spring.rabbitmq.listener.simple.default-requeue-rejected=false

rabbitmq.queue.name = appointment_created_queue
rabbitmq.exchange.name = appointment_created_exchange
rabbitmq.routing.key = appointment_created_key

# Notification queue configuration
rabbitmq.notification.queue.name = appointment_confirmed_queue
rabbitmq.notification.routing.key = appointment_confirmed_key

#Appointment cancellation queue configuration
rabbitmq.cancellation.queue.name = appointment_cancelled_queue
rabbitmq.cancellation.routing.key = appointment_cancelled_key

# RabbitMQ Debug Logging
logging.level.org.springframework.amqp=DEBUG
logging.level.com.rabbitmq=DEBUG

# Redis Configuration
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.timeout=60000
# Cache debugging
logging.level.org.springframework.cache=DEBUG
logging.level.org.springframework.data.redis=DEBUG

